# Linear algebra review

We usually use numpy for linear algebra. Operations here are implemented with extreme efficiency!

In [2]:
import numpy as np


## 1. Creating matrices and vectors

### Creating a matrix

There are different ways to created matrices. We might want to create a matrix completely manually:

In [3]:
A = np.array([[1, 0, 2, 4], [2, 1, 3, 1], [3, 1, 0, 2]])

A.shape

(3, 4)

Alternatively, we could create specific types of matrices, either because we want to use those directly, or as placeholders to fill up later:

In [4]:
A = np.zeros((3, 4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
A = np.ones((3, 4))
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
A = np.full((3, 4), 6)
A

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [7]:
A = np.eye(3)
A


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

To access one or multiple elements in a matrix, we use the usual indexing methods:

In [8]:
A = np.array([[1, 0, 2, 4], [2, 1, 3, 1], [3, 1, 0, 2]])
print(A[1, 2])  # 3
print(A[2, 1:3])  # [1,0]
print(A[:, 3])  # [4,1,2]

3
[1 0]
[4 1 2]


### Creating a vector

First try: from list

In [9]:
x_one_dim = np.array([2, 1, 3])
x_one_dim.shape

(3,)

The problem with using one-dimensional vectors is that we may run into problems when doing operations on our matrices and vector later on. Generally, you should aim to use matrics instead of vectors where one dimension is one:

In [10]:
x_two_dim = np.array([[2], [1], [3]])
x_two_dim.shape

(3, 1)

Of course, that's not the most efficient way to do things. Instead, we can also use the one-dimensional vector and reshape it:

In [10]:
x_one_dim = np.array([2, 1, 3])
x_two_dim = x_one_dim.reshape((3, 1))
x_two_dim

array([[2],
       [1],
       [3]])

We can easily add two vectors together:

In [13]:
print(x_two_dim + x_two_dim)
print(np.add(x_two_dim, x_two_dim))

[[4]
 [2]
 [6]]
[[4]
 [2]
 [6]]


### Broadcasting

Broadcasting allows us to work with arrays of different sizes when doing arithmetic operations. We will stick to additions for now, but the same logic applies when we do element-wise multiplication.

Say we have a matrix $A \in \mathcal{R}^{4 \times 3}$ and a (row-vector) $x \in \mathcal{R}^3$. We want to add $x$ **to each row** of $A$

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
B = np.empty_like(A)  # Creates an empty matrix of the same shape as A
x = np.array([1, 0, 2]).reshape((1, 3))

Let's do this in the most straightforward way, with a loop:

In [15]:
for i in range(4):
    print(i)
    B[i, :] = A[i, :] + x
print(B)


0
1
2
3
[[ 2  2  5]
 [ 5  5  8]
 [ 8  8 11]
 [11 11 14]]


This is quite tedious. In fact, if we have a large matrix, this will run very long, too. Broadcasting allows us to do this much more effectively:

In [16]:
B = A + x
print(B)


[[ 2  2  5]
 [ 5  5  8]
 [ 8  8 11]
 [11 11 14]]


What happens here? The $x$ is treated as if $x = \begin{pmatrix}1 & 0 & 2\\1 & 0 & 2\\1 & 0 & 2\end{pmatrix}$, to be able to do additions with $A$.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
1. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
1. The arrays can be broadcast together if they are compatible in all dimensions.
1. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
1. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension
If this explanation does not make sense, try reading the explanation [from the documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or [this explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

## 2. Operations on vectors and matrices

### Multiplication

Let's start with multiplying two vectors. Try out the following:

In [18]:
x = np.array([2, 1, 3]).reshape((3, 1))
print(x)
y = np.array([1, 0, 2]).reshape((3, 1))
print(y)
x * y

[[2]
 [1]
 [3]]
[[1]
 [0]
 [2]]


array([[2],
       [0],
       [6]])

In [28]:
print((x.T).shape)
print((y).shape)
print("The dot product of the x and y.T is a 1X1 matrix. See the below")

(1, 3)
(3, 1)
The dot product of the x and y.T is a 1X1 matrix. See the below


The above does **NOT** give us the dot-product. Instead, each entries are multiplied element-wise! For the dot-product, we use the `.dot` function:

In [19]:
np.dot(x.T, y)

array([[8]])

Note here that we had to make sure first that the two vectors are properly aligned (using the transpose). Try it without:

In [23]:
np.dot(x, y)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [26]:
print((x).shape)
print((y.T).shape)
print("The dot product of the x and y.T is a 3X3 matrix. See the below.")

(3, 1)
(1, 3)
The dot product of the x and y.T is a 3X3 matrix


Naturally, we can get the outer product by arranging the vectors in the right way:

In [21]:
np.dot(x, y.T)

array([[2, 0, 4],
       [1, 0, 2],
       [3, 0, 6]])

Let's try multiplying a matrix and a vector now:

In [ ]:
A = np.array([[1, 0, 2, 4], [2, 1, 3, 1], [3, 1, 0, 2]])
x = np.array([2, 1, 3]).reshape((3, 1))
A * x

As before, we are doing element-wise multiplication. Notice how the vector `x` is repeated and multiplied with each of the columns of `A`. Of course, we can also perform an actual matrix-multiplication, but only with the right dimensions:

In [ ]:
print(A.shape)
print(A.T.shape)


In [ ]:
np.dot(A.T, x)

If a matrix is invertible, we can easily get its inverse with `numpy`:

In [ ]:
A = np.array([[1, 0, 2], [2, 1, 3], [3, 1, 0]])
np.linalg.inv(A)

Careful that the matrix is actually invertible:

In [ ]:
A = np.array([[1, 0, 1], [2, 1, 3], [2, 0, 2]])
np.linalg.inv(A)

### Eigenvectors and SVD

We can get both the eigenvectors and eigenvalues from `numpy` (assuming a square matrix):

In [3]:
A = np.array([[1, 0, 1], [2, 1, 3], [3, 1, 0]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 3.17740968  0.67836283 -1.85577251]
Eigenvectors:
[[-0.21772116 -0.29539583 -0.26312244]
 [-0.85314528  0.95063892 -0.60509323]
 [-0.47406816  0.09501028  0.75141783]]


Similar with the singular value decomposition:

In [4]:
U, S, Vtranspose = np.linalg.svd(A)
print("U:")
print(U)
print("Sigmas:")
print(S)
print("V:")
print(Vtranspose.T)


U:
[[-0.29152938 -0.11941745 -0.94907855]
 [-0.77024208 -0.55903255  0.30693606]
 [-0.56721933  0.82050111  0.07099407]]
Sigmas:
[4.58774145 2.18953402 0.39820743]
V:
[[-0.77024208  0.55903255 -0.30693606]
 [-0.29152938  0.11941745  0.94907855]
 [-0.56721933 -0.82050111 -0.07099407]]
